### PR TITLE
Bug/22 fix send keys with key hold method

### LINKED ISSUE #22: SendKeysWithKeyHold of element's KeyboardActions fails when element is disappeared
ReleaseKey should be performed without target element for such cases

### PR DESCRIPTION
**Pull request by mialeska**
Add root session into the keyboard actions in order to release the key when the window is closed #22

### CODE REVIEW

**Review by paveliam — APPROVED** [review]

File: Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Element.cs [hunk 1]
```diff
@@ -24,15 +25,17 @@ protected Element(By locator, string name, ElementState elementState = ElementSt
 
         protected override IApplication Application => AqualityServices.Application;
 
-        protected override ConditionalWait ConditionalWait => AqualityServices.ConditionalWait;
+        protected virtual WindowsDriver<WindowsElement> WindowsDriver => AqualityServices.Application.Driver;
+
+        protected override ConditionalWait ConditionalWait => AqualityServices.Get<ConditionalWait>();
```
Comment (knysh) [inline Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Element.cs]: AqualityServices.ConditionalWait;

**Review by knysh — APPROVED** [review]

File: Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Element.cs (hunk 1 above)
Comment (mialeska) [reply Aquality.WinAppDriver/src/Aquality.WinAppDriver/Elements/Element.cs]: fixed
